### PR TITLE
Test

### PR DESCRIPTION
**Pull request by OlgaTPark**

### CODE REVIEW

**Comment by classilla** [comment]
I'm not opposed to these changes, but I don't know for what reason you've submitted them.

**Comment by OlgaTPark** [comment]
This was an error from me while testing GitHub.  
In fact, I tried to build TenFourFox for Intel and I succeeded to build and run TFX esr24 and esr31 (I'm still getting issues with newer versions).  I made modifications to the source code in order to build with the SDK of Mac OS X 10.5 and to (re-)enable some features on 10.5.  For the moment I did not published my work because I'm still checking it (and mostly replacing `#if (0)` by  `#if MAC_OS_X_VERSION_MIN_REQUIRED <=  1050`).  
This was a test (as is name implies) for an eventual publication of my modifications and I didn't know that the 'pull' button was a way to merge with the original repository.  

I apologize for the inconvenience.

**Comment by classilla** [comment]
> I apologize for the inconvenience.

Don't apologize, I'm delighted someone is doing this. Yes, I pretty much
gave up on the 10.5 SDK, so that had rotted and I got lazy. All I ask is
to try to do pull requests in chunks so I don't have a huge clot to review
all at once. Feel free to open issues for those with the PRs attached and
I'll go through them.

I suspect the major issue you're seeing with 38ESR and 45ESR is that the
JavaScript backend changed dramatically and I did a number of hacks to the
engine to get it to work with PowerPC. Those will have to be #ifdef __ppc__
or something. If you look at the 45.9 changesets, you should be able to
see exactly where I did this.

Obviously it goes without saying that whatever changes you make can't
break building against the 10.4 SDK or on PowerPC, but other than that,
I'm very happy to hear someone has taken this on. Please ask if you need
advice or suggestions on anything.

**Comment by OlgaTPark** [comment]
Hello,  
I know it has been a while in which I didn't gave any news.  Since last time I tried again to patch and build TFX esr45 for Intel from scratch and after long bug-fixing I finally succeeded to run a (stable enough) TenFiveFox 45.9 (not too early)!  Downside, my build is a total cheat.  I took the source code of Firefox ESR 45.9.1 and applied only certain of your modifications after (long) checking with FileMerge.  This explain why I'm so slow, why merging might be tricky and (maybe) why it works.   
Now let's talk about the future:  
* I will continue to develop an Intel version of TenFourFox (at least for Mac OS X 10.5 - because I need it);  
* For TFX esr38, I'll drop it since the build toolchain is completely broken in this version, even whith [Mozilla Bug 1063880](http://bugzilla.mozilla.org/show_bug.cgi?id=1063880) applied and I don't want to bother anymore with it (and I think version 45 have more priority);  
* Concerning the publication of my source code, I will fork your repository on my GitHub account, create a new `Intel` branch from your [hello FPR](https://github.com/classilla/tenfourfox/commit/c9b2922b70d0052b78a1a9bc6069cefe5a119124) commit and add my changes to it.  You'll be able to trigger Pull Requests when you want, at least if you agree to work that way!  
* I'll also publish some of my work on older versions on [the repository you already found](http://github.com/OlgaTPark/TenFourFoxIntel) but without priority;  
* Once I'll finish TenFourFox 45.9 (I mean, when I'll reach "Source Parity" with your code), I'll upload some builds and then try to upgrade my `Intel` branch to FPR1, 2, 3, etc.  
*  I think I will make a x86 TenFourFox build for Tiger, a x86 (and maybe x64) TenFiveFox build fo Leopard and a x86 + x64 TenSixFox build for Snow Leopard up to Mountain Lion in order to enable the maximum features for these respective OSes;  

This probably sounds great (and I hope that it will be) but I cannot offer guaranties that the Intel version will be released soon or will simply be.  Please understand that TenFourFox is not my principal activity but this publication is my way to thank you from saving my 10.5 MacBook.  Also, please do not make official annoncement (as you already did on your [blogspot](http://tenfourfox.blogspot.be/2017/05/feature-parity-release-finally-preview.html)) because I do not want to give fake hope to people following you.  A last note: the name visible on my GitHub account is not my true name, I'm just an anonymous enthusiast and contributor.  

Again, thank you for all your hard work in backward-compatibility and good continuation with TenFourFox.

**Comment by classilla** [comment]
No worries, I'll not make any more public references until/if there is a release. That sounds like a really complete set of builds, and very promising! Is the difference the SDK each version is compiled against?

Some of the more recent updates the last day or two have PowerPC-specific stuff I added to them. I've tried to mark this, but there might be some unexpected `#error` traps with the different endianness (on the other hand, that should easily show where the problem is).

I don't mind working in the way you suggest, though there may be some additional merge overhead on your end. Whatever you think best.

Obviously, if this comes to fruition, like the old Intel 17.0.2 build it would be offered with absolutely no support so as not to burden you with that.

**Comment by OlgaTPark** [comment]
My new branch is available here: <http://github.com/OlgaTPark/tenfourfox/tree/Intel> and I already uploaded [my first commit](http://github.com/OlgaTPark/tenfourfox/commit/acd74adabfe90fc94696585a0468d71d8c47920a) on it.  Don't hesitate if you have questions about my work.

For TenFour|Five|SixFox builds, I intend to use conditional compilation with `MAC_OS_X_VERSION_MIN_REQUIRED` and changing the SDK for each Ten*Fox variant.  There's also some `.mozconfig` changes.

As I said before, I'm checking nearly every change you made to the original Firefox code and if I need to disable some PowerPC-specific stuff on Intel, I'll do it.  Unfortunately, I do not want to update my branch to TenFourFox FPR before I'll reach _Source Parity_ with your TenFourFox 45.9 in order to have something perfect (and easy to merge)…

The remainder will come laaaater…

Thank you for allowing me to make this possible.

**Comment by classilla** [comment]
> Thank you for allowing me to make this possible.

No, thank *you* for doing it!

**Pull request closed without merging**
