### PR TITLE
part of tweaks

### PR DESCRIPTION
**Pull request by rmottola**
subset of the "clean" fixes that finally fixed font issues and stopped crashing the jit, so others can benefit

### CODE REVIEW

**Comment by classilla** [comment]
48a8e41 needs to be fixed to avoid causing #495 for the JS shell.

**Comment by rmottola** [comment]
CPU_ARCH has been fixed as well two minor tweaks for Intel only (missing libmozglue)
Now fine?

**Comment by classilla** [comment]
I'd like whatever else had to be added to make @kencu's build work, and I'll take it first thing in FPR8 timeframe.

**Comment by classilla** [comment]
Does this include enabling `ctypes`? I see the fix for `libffi`.

**Comment by rmottola** [comment]
libffi fix is needed for ctypes, which just need to be enabled in the mozconfig. Ken tested it and it is fine

**Pull request merged**
